name: Get contracts from repo

on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  use_api_via_script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.0"
          # global cache directory
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      # will cache node modules and only re-install them only if yarn.lock get updated
      - name: setup cache node_modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install modules
        run: yarn install

      - name: Install dependencies
        run: yarn add node-fetch

      - name: Run script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          UPDATE_CONTRACTS_SECRET: ${{ secrets.UPDATE_CONTRACTS_SECRET }}
          CONTRACTS_API_URL: ${{ secrets.CONTRACTS_API_URL }}
        run: |
          yarn run update-contracts
